//! # Nova Chunker V2 — Novel-Specialized Three-Layer Pipeline
//!
//! Architecture:
//! - Layer 0: Document preprocessing (chapter detection, language, metadata)
//! - Layer 1: Semantic chunking (sentence-boundary aware, dialogue protection)
//! - Layer 2: Contextual enrichment (context prefix generation)
//! - Layer 3: Metadata injection for indexing
//!
//! Key innovations over v1:
//! - Chapter-aware splitting (中文/日文/英文 chapter markers)
//! - Dialogue protection (never split mid-quote)
//! - Range-based capacity (300..512 tokens instead of fixed 512)
//! - Zero overlap (Chroma research proves reranker compensates)
//! - Improved CJK token estimation (Qwen3 BPE-aware)

use regex::Regex;
use serde::{Deserialize, Serialize};
use std::sync::LazyLock;
use unicode_segmentation::UnicodeSegmentation;

// ─── Configuration ───────────────────────────────────────────────────────────

/// Advanced chunking configuration for novel content.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkingConfigV2 {
    /// Minimum tokens per chunk (avoid too-short fragments)
    pub min_tokens: usize,
    /// Target range lower bound
    pub target_min_tokens: usize,
    /// Target range upper bound
    pub target_max_tokens: usize,
    /// Absolute maximum (for dialogue-heavy sections)
    pub max_tokens: usize,
    /// Overlap tokens (0 recommended with reranker)
    pub overlap_tokens: usize,
    /// Context prefix token budget for Contextual Retrieval
    pub context_prefix_tokens: usize,
}

impl Default for ChunkingConfigV2 {
    fn default() -> Self {
        Self {
            min_tokens: 200,
            target_min_tokens: 300,
            target_max_tokens: 512,
            max_tokens: 640,
            overlap_tokens: 0,
            context_prefix_tokens: 80,
        }
    }
}

// ─── Types ───────────────────────────────────────────────────────────────────

/// Detected language of content.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ContentLanguage {
    Chinese,
    Japanese,
    Korean,
    English,
    Mixed,
}

/// A detected chapter boundary.
#[derive(Debug, Clone)]
pub struct ChapterBoundary {
    pub title: String,
    pub start_byte: usize,
    pub index: usize,
}

/// A chunk produced by the v2 pipeline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkV2 {
    pub index: usize,
    pub content: String,
    pub token_estimate: usize,
    pub start_offset: usize,
    pub end_offset: usize,
    /// Chapter title this chunk belongs to
    pub chapter_title: Option<String>,
    /// Chapter index within the document
    pub chapter_index: usize,
    /// Language detected
    pub language: ContentLanguage,
    /// Whether this chunk is primarily dialogue
    pub is_dialogue: bool,
    /// Contextual prefix (generated by Layer 2, initially empty)
    pub context_prefix: String,
}

// ─── Layer 0: Document Preprocessing ─────────────────────────────────────────

/// Chapter detection patterns for multiple languages.
static CHAPTER_PATTERNS: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    vec![
        // Chinese: 第X章/节/回/卷/集/篇
        Regex::new(r"(?m)^\s*第[一二三四五六七八九十百千零\d]+[章节回卷集篇].*$").unwrap(),
        // Japanese: 第X章/話/回/巻/編
        Regex::new(r"(?m)^\s*第[一二三四五六七八九十百千零\d]+[章話回巻編].*$").unwrap(),
        // English: Chapter/Part/Book/Act/Section N
        Regex::new(r"(?im)^\s*(chapter|part|book|act|section)\s+\d+.*$").unwrap(),
        // Horizontal line separators (─━═)
        Regex::new(r"(?m)^\s*[─━═]{3,}\s*$").unwrap(),
        // Scene break markers (* * *)
        Regex::new(r"(?m)^\s*\*\s*\*\s*\*\s*$").unwrap(),
        // Numbered chapter (1. / 01 / ①)
        Regex::new(r"(?m)^\s*[①②③④⑤⑥⑦⑧⑨⑩\d]+[\.、]\s+.+$").unwrap(),
    ]
});

/// CJK quote pairs for dialogue detection.
static DIALOGUE_OPEN: &[char] = &['「', '『', '"', '"', '（', '【', '《'];
static DIALOGUE_CLOSE: &[char] = &['」', '』', '"', '"', '）', '】', '》'];

/// Detect primary language of text.
pub fn detect_language(text: &str) -> ContentLanguage {
    let sample = &text[..text.len().min(2000)];
    let mut cjk_chars = 0u32;
    let mut latin_chars = 0u32;
    let mut jp_specific = 0u32;
    let mut kr_specific = 0u32;

    for c in sample.chars() {
        let cp = c as u32;
        match cp {
            // CJK Unified Ideographs
            0x4E00..=0x9FFF | 0x3400..=0x4DBF => cjk_chars += 1,
            // Hiragana + Katakana
            0x3040..=0x309F | 0x30A0..=0x30FF => jp_specific += 1,
            // Hangul
            0xAC00..=0xD7AF | 0x1100..=0x11FF => kr_specific += 1,
            // Basic Latin
            0x0041..=0x007A => latin_chars += 1,
            _ => {}
        }
    }

    let total = (cjk_chars + latin_chars + jp_specific + kr_specific).max(1);

    if kr_specific as f32 / total as f32 > 0.15 {
        ContentLanguage::Korean
    } else if jp_specific as f32 / total as f32 > 0.15 {
        ContentLanguage::Japanese
    } else if cjk_chars as f32 / total as f32 > 0.3 {
        ContentLanguage::Chinese
    } else if latin_chars as f32 / total as f32 > 0.5 {
        ContentLanguage::English
    } else {
        ContentLanguage::Mixed
    }
}

/// Detect chapter boundaries in the document.
pub fn detect_chapters(text: &str) -> Vec<ChapterBoundary> {
    let mut boundaries = Vec::new();

    for pattern in CHAPTER_PATTERNS.iter() {
        for mat in pattern.find_iter(text) {
            boundaries.push(ChapterBoundary {
                title: mat.as_str().trim().to_string(),
                start_byte: mat.start(),
                index: 0, // Will be assigned after sorting
            });
        }
    }

    // Sort by position and deduplicate nearby boundaries
    boundaries.sort_by_key(|b| b.start_byte);
    boundaries.dedup_by(|a, b| a.start_byte.abs_diff(b.start_byte) < 10);

    // Assign sequential indices
    for (i, b) in boundaries.iter_mut().enumerate() {
        b.index = i;
    }

    boundaries
}

// ─── Layer 1: Semantic Chunking ──────────────────────────────────────────────

/// The main V2 chunker.
pub struct NovelChunker {
    config: ChunkingConfigV2,
}

impl NovelChunker {
    pub fn new(config: ChunkingConfigV2) -> Self {
        Self { config }
    }

    /// Full pipeline: preprocess → chunk → enrich metadata.
    /// Layer 2 (contextual prefix) requires async LLM call and is done separately.
    pub fn chunk_document(
        &self,
        text: &str,
        book_title: Option<&str>,
    ) -> Vec<ChunkV2> {
        if text.is_empty() {
            return Vec::new();
        }

        let language = detect_language(text);
        let chapters = detect_chapters(text);

        if chapters.is_empty() {
            // No chapters detected — treat whole document as one chapter
            return self.chunk_section(text, 0, None, 0, language);
        }

        let mut all_chunks = Vec::new();
        let mut global_chunk_idx = 0;

        for (ci, chapter) in chapters.iter().enumerate() {
            let section_end = chapters
                .get(ci + 1)
                .map(|next| next.start_byte)
                .unwrap_or(text.len());

            // Skip the chapter title line itself
            let content_start = text[chapter.start_byte..]
                .find('\n')
                .map(|pos| chapter.start_byte + pos + 1)
                .unwrap_or(chapter.start_byte);

            if content_start >= section_end {
                continue;
            }

            let section = &text[content_start..section_end];
            let chapter_title = Some(chapter.title.as_str());

            let mut section_chunks = self.chunk_section(
                section,
                content_start,
                chapter_title,
                ci,
                language,
            );

            // Fix global indices
            for chunk in &mut section_chunks {
                chunk.index = global_chunk_idx;
                global_chunk_idx += 1;
            }

            all_chunks.extend(section_chunks);
        }

        // Handle content before the first chapter
        if let Some(first) = chapters.first() {
            if first.start_byte > 0 {
                let preamble = &text[..first.start_byte];
                if estimate_tokens_v2(preamble, language) >= self.config.min_tokens {
                    let mut preamble_chunks = self.chunk_section(
                        preamble,
                        0,
                        book_title.or(Some("序言")),
                        0,
                        language,
                    );
                    // Insert at beginning, shift all indices
                    let offset = preamble_chunks.len();
                    for chunk in all_chunks.iter_mut() {
                        chunk.index += offset;
                    }
                    for (i, chunk) in preamble_chunks.iter_mut().enumerate() {
                        chunk.index = i;
                    }
                    preamble_chunks.extend(all_chunks);
                    all_chunks = preamble_chunks;
                }
            }
        }

        all_chunks
    }

    /// Chunk a single section (chapter or fragment) respecting dialogue boundaries.
    fn chunk_section(
        &self,
        text: &str,
        base_offset: usize,
        chapter_title: Option<&str>,
        chapter_index: usize,
        language: ContentLanguage,
    ) -> Vec<ChunkV2> {
        // Split into sentences using Unicode segmentation
        let sentences = split_into_sentences(text, language);

        let mut chunks: Vec<ChunkV2> = Vec::new();
        let mut current_tokens = 0usize;
        let mut current_start = 0usize;
        let mut current_sentences: Vec<&str> = Vec::new();
        let mut in_dialogue = false;
        let mut dialogue_depth = 0u32;

        for sentence in &sentences {
            let sent_tokens = estimate_tokens_v2(sentence, language);

            // Dialogue protection: track quote depth
            for c in sentence.chars() {
                if DIALOGUE_OPEN.contains(&c) {
                    dialogue_depth += 1;
                    in_dialogue = true;
                } else if DIALOGUE_CLOSE.contains(&c) {
                    dialogue_depth = dialogue_depth.saturating_sub(1);
                    if dialogue_depth == 0 {
                        in_dialogue = false;
                    }
                }
            }

            let would_be = current_tokens + sent_tokens;

            // Decision: should we emit current chunk?
            let should_emit = if in_dialogue && dialogue_depth > 0 {
                // Inside dialogue: allow elastic expansion up to max_tokens
                would_be > self.config.max_tokens
            } else {
                // Normal: emit when exceeding target_max
                would_be > self.config.target_max_tokens && current_tokens >= self.config.min_tokens
            };

            if should_emit && !current_sentences.is_empty() {
                // Emit chunk
                let content = current_sentences.join("");
                let content_bytes = content.len();
                let is_dialogue_chunk = content.chars()
                    .filter(|c| DIALOGUE_OPEN.contains(c) || DIALOGUE_CLOSE.contains(c))
                    .count() >= 4;

                chunks.push(ChunkV2 {
                    index: chunks.len(),
                    content,
                    token_estimate: current_tokens,
                    start_offset: base_offset + current_start,
                    end_offset: base_offset + current_start + content_bytes,
                    chapter_title: chapter_title.map(String::from),
                    chapter_index,
                    language,
                    is_dialogue: is_dialogue_chunk,
                    context_prefix: String::new(),
                });

                // Start new chunk (no overlap in v2)
                current_start += content_bytes;
                current_sentences.clear();
                current_tokens = 0;
            }

            current_sentences.push(sentence);
            current_tokens += sent_tokens;
        }

        // Final chunk
        if !current_sentences.is_empty() {
            let content = current_sentences.join("");
            let content_bytes = content.len();
            let is_dialogue_chunk = content.chars()
                .filter(|c| DIALOGUE_OPEN.contains(c) || DIALOGUE_CLOSE.contains(c))
                .count() >= 4;

            if current_tokens >= self.config.min_tokens || chunks.is_empty() {
                chunks.push(ChunkV2 {
                    index: chunks.len(),
                    content,
                    token_estimate: current_tokens,
                    start_offset: base_offset + current_start,
                    end_offset: base_offset + current_start + content_bytes,
                    chapter_title: chapter_title.map(String::from),
                    chapter_index,
                    language,
                    is_dialogue: is_dialogue_chunk,
                    context_prefix: String::new(),
                });
            } else if let Some(last) = chunks.last_mut() {
                // Merge short trailing fragment into previous chunk
                last.content.push_str(&content);
                last.token_estimate += current_tokens;
                last.end_offset = base_offset + current_start + content_bytes;
            }
        }

        chunks
    }
}

// ─── Sentence Splitting ──────────────────────────────────────────────────────

/// Split text into sentences, respecting language-specific boundaries.
fn split_into_sentences(text: &str, language: ContentLanguage) -> Vec<&str> {
    match language {
        ContentLanguage::English => {
            // Use Unicode sentence boundaries for English
            UnicodeSegmentation::unicode_sentences(text).collect()
        }
        _ => {
            // For CJK: split on sentence-ending punctuation but preserve the punctuation
            split_cjk_sentences(text)
        }
    }
}

/// Split CJK text into sentences at natural boundaries.
/// Keeps punctuation attached to the sentence.
fn split_cjk_sentences(text: &str) -> Vec<&str> {
    let sentence_ends: &[char] = &['。', '！', '？', '…', '．', '!', '?', '\n'];
    let mut sentences = Vec::new();
    let mut start = 0;

    let chars: Vec<(usize, char)> = text.char_indices().collect();
    let mut i = 0;

    while i < chars.len() {
        let (_, c) = chars[i];

        if sentence_ends.contains(&c) {
            // Include trailing punctuation and whitespace
            let mut end_idx = i + 1;
            while end_idx < chars.len() {
                let next_c = chars[end_idx].1;
                if next_c == '\n' || next_c == '\r' || next_c == ' ' || next_c == '　' {
                    end_idx += 1;
                } else {
                    break;
                }
            }

            let end_byte = if end_idx < chars.len() {
                chars[end_idx].0
            } else {
                text.len()
            };

            let sentence = &text[start..end_byte];
            if !sentence.trim().is_empty() {
                sentences.push(sentence);
            }
            start = end_byte;
            i = end_idx;
        } else {
            i += 1;
        }
    }

    // Remaining text
    if start < text.len() {
        let remaining = &text[start..];
        if !remaining.trim().is_empty() {
            sentences.push(remaining);
        }
    }

    sentences
}

// ─── Token Estimation V2 ─────────────────────────────────────────────────────

/// Improved token estimation accounting for Qwen3 BPE behavior.
/// Qwen3 BPE: CJK is roughly 0.6-0.8 tokens per character (many 2-3 char compounds = 1 token).
/// English: ~1.3 tokens per word.
pub fn estimate_tokens_v2(text: &str, language: ContentLanguage) -> usize {
    let mut cjk_chars = 0u32;
    let mut latin_words = 0u32;
    let mut in_word = false;
    let mut punct_count = 0u32;

    for c in text.chars() {
        let cp = c as u32;
        match cp {
            // CJK ranges
            0x4E00..=0x9FFF | 0x3400..=0x4DBF | 0x3040..=0x30FF | 0xAC00..=0xD7AF => {
                cjk_chars += 1;
                in_word = false;
            }
            // ASCII alphanumeric
            0x0030..=0x0039 | 0x0041..=0x005A | 0x0061..=0x007A => {
                if !in_word {
                    latin_words += 1;
                    in_word = true;
                }
            }
            // Punctuation (most are single tokens)
            _ if c.is_ascii_punctuation() || "。、！？；：「」『』（）【】《》".contains(c) => {
                punct_count += 1;
                in_word = false;
            }
            _ => {
                in_word = false;
            }
        }
    }

    let (cjk_factor, latin_factor, punct_factor) = match language {
        ContentLanguage::Chinese => (0.7, 1.3, 0.5),
        ContentLanguage::Japanese => (0.8, 1.3, 0.6),
        ContentLanguage::Korean => (0.9, 1.3, 0.6),
        ContentLanguage::English => (1.0, 1.3, 0.5),
        ContentLanguage::Mixed => (0.8, 1.25, 0.5),
    };

    // Qwen3 BPE estimation:
    // - CJK-language text often merges compounds into fewer tokens
    // - English words average slightly more than one token
    // - Punctuation frequently merges with adjacent tokens
    let cjk_tokens = (cjk_chars as f64 * cjk_factor) as usize;
    let latin_tokens = (latin_words as f64 * latin_factor) as usize;
    let punct_tokens = (punct_count as f64 * punct_factor) as usize;

    (cjk_tokens + latin_tokens + punct_tokens).max(1)
}

// ─── Layer 2: Contextual Retrieval ──────────────────────────────────────────

/// Generate a contextual retrieval prompt for a chunk.
/// This prompt is sent to an LLM to generate a 50-100 token context prefix.
pub fn build_context_prompt(
    chunk: &ChunkV2,
    prev_chunk_summary: Option<&str>,
    book_title: Option<&str>,
) -> String {
    let chapter_info = chunk.chapter_title
        .as_deref()
        .unwrap_or("(未知章节)");

    let book_info = book_title.unwrap_or("(未知书籍)");

    let prev_info = prev_chunk_summary
        .map(|s| format!("\n前文摘要: {}", s))
        .unwrap_or_default();

    format!(
        r#"<document>
书籍: {book_info}
章节: {chapter_info}{prev_info}
</document>

请为以下文本块生成一个简短的上下文描述（50-80字），帮助理解这段文字在整部作品中的位置和背景。
只输出上下文描述，不要其他内容。

<chunk>
{content}
</chunk>"#,
        content = &chunk.content[..chunk.content.len().min(500)]
    )
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_language_detection() {
        assert_eq!(detect_language("这是一段中文测试文本"), ContentLanguage::Chinese);
        assert_eq!(detect_language("This is an English test"), ContentLanguage::English);
        assert_eq!(detect_language("これは日本語のテストです"), ContentLanguage::Japanese);
    }

    #[test]
    fn test_chapter_detection_chinese() {
        let text = "前言内容\n\n第一章 初入江湖\n\n正文内容开始\n\n第二章 峰回路转\n\n更多内容";
        let chapters = detect_chapters(text);
        assert_eq!(chapters.len(), 2);
        assert!(chapters[0].title.contains("第一章"));
        assert!(chapters[1].title.contains("第二章"));
    }

    #[test]
    fn test_chapter_detection_english() {
        let text = "Prologue\n\nChapter 1 The Beginning\n\nContent here\n\nChapter 2 The Middle\n\nMore content";
        let chapters = detect_chapters(text);
        assert_eq!(chapters.len(), 2);
    }

    #[test]
    fn test_chunking_with_chapters() {
        let chunker = NovelChunker::new(ChunkingConfigV2 {
            min_tokens: 10,
            target_min_tokens: 20,
            target_max_tokens: 50,
            max_tokens: 80,
            overlap_tokens: 0,
            context_prefix_tokens: 0,
        });

        let text = "第一章 开始\n\n这是第一章的内容。这里有很多文字需要被切分成多个块。每个句子都包含一些有意义的内容。\n这是另一个段落。包含更多的故事情节。\n\n第二章 继续\n\n第二章的故事继续展开。新的角色登场了。";
        let chunks = chunker.chunk_document(text, Some("测试小说"));
        assert!(chunks.len() >= 2, "Should produce multiple chunks across chapters");

        // Verify chapter assignment
        let ch1_chunks: Vec<_> = chunks.iter().filter(|c| c.chapter_index == 0).collect();
        let ch2_chunks: Vec<_> = chunks.iter().filter(|c| c.chapter_index == 1).collect();
        assert!(!ch1_chunks.is_empty());
        assert!(!ch2_chunks.is_empty());
    }

    #[test]
    fn test_dialogue_protection() {
        let chunker = NovelChunker::new(ChunkingConfigV2 {
            min_tokens: 5,
            target_min_tokens: 10,
            target_max_tokens: 30,
            max_tokens: 60,
            overlap_tokens: 0,
            context_prefix_tokens: 0,
        });

        let text = "他说：「这是一段很长的对话。我要讲很多事情。关于那件事，你必须要知道。」她点了点头。";
        let chunks = chunker.chunk_document(text, None);

        // Dialogue should not be split in the middle
        for chunk in &chunks {
            let opens: usize = chunk.content.chars().filter(|c| *c == '「' || *c == '『').count();
            let closes: usize = chunk.content.chars().filter(|c| *c == '」' || *c == '』').count();
            // In a well-formed chunk, opens should equal closes (or differ by at most 1 at boundaries)
            assert!(
                opens.abs_diff(closes) <= 1,
                "Dialogue split detected: opens={}, closes={} in '{}'",
                opens, closes, &chunk.content[..chunk.content.len().min(50)]
            );
        }
    }

    #[test]
    fn test_token_estimation_v2() {
        // Pure Chinese: ~0.7 tokens per char
        let tokens = estimate_tokens_v2("这是一段中文测试", ContentLanguage::Chinese);
        assert!(tokens >= 4 && tokens <= 8, "Chinese token estimate: {}", tokens);

        // English: ~1.3 per word
        let tokens = estimate_tokens_v2("This is a simple test sentence", ContentLanguage::English);
        assert!(tokens >= 6 && tokens <= 10, "English token estimate: {}", tokens);
    }
}
